Fix URL path
> Error: sokoloffa/radiola/radiola: Download failed on Cask 'radiola' with message: Download failed: https://github.com/SokoloffA/radiola/releases/download/v7.0/Radiola-7.0.2.dmg

Sorry, I broke it or something changed about the structure of the release tags. This PR should fix it.